project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - workshop/
    - advanced/
    - cases/
    - bibliography/
    - resources/

website:
  title: "Targeted Learning for Real-World Evidence"
  repo-url: https://github.com/amertens/causal-learning-handbook
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Workshop
        href: workshop/index.qmd
      - text: Estimands
        href: estimands/index.qmd
      - text: Advanced
        href: advanced/index.qmd
      - text: Case Studies
        href: cases/index.qmd
      - text: Bibliography
        href: bibliography/index.qmd
      - text: Resources
        href: resources/index.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    smooth-scroll: true
