project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - workshop/
    - advanced/
    - cases/
    - bibliography/
    - resources/

website:
  title: "Targeted Learning for Real-World Evidence"
  repo-url: https://github.com/amertens/causal-learning-handbook
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Workshop
        href: workshop/index.qmd
        sidebar: workshop
      - text: Estimands
        href: estimands/index.qmd
        sidebar: estimands
      - text: Advanced
        href: advanced/index.qmd
        sidebar: advanced
      - text: Case Studies
        href: cases/index.qmd
      - text: Bibliography
        href: bibliography/index.qmd
      - text: Resources
        href: resources/index.qmd
  page-navigation: true

  sidebar:
    - id: workshop
      title: "Workshop"
      style: "docked"
      search: true
      contents:
        - workshop/index.qmd
        - workshop/SER_workshop.qmd
    - id: estimands
      title: "Estimands"
      style: "docked"
      search: true
      contents:
        - estimands/index.qmd
        - estimands/step1_causal_estimand.qmd
        - estimands/step2_causal_model.qmd
        - estimands/step3_identification.qmd
    - id: advanced
      title: "Advanced"
      style: "docked"
      search: true
      contents:
        - advanced/index.qmd
        - text: "1.1 Regression vs Causal Inference"
          href: advanced/01-01-regression-vs-causal.qmd
        - text: "1.2 The Causal Roadmap in detail"
          href: advanced/01-02-causal-roadmap.qmd
        - text: "1.3 Identification and Estimands"
          href: advanced/01-03-identification-estimands.qmd
        - text: "2.1 G-computation"
          href: advanced/02-01-gcomputation.qmd
        - text: "2.2 Inverse Probability of Treatment Weighting (IPTW)"
          href: advanced/02-02-iptw.qmd
        - text: "2.3 Doubly Robust Estimation and Targeted Maximum Likelihood Estimation (TMLE)"
          href: advanced/02-03-doubly-robust-tmle.qmd
        - text: "2.4 Super Learner"
          href: advanced/02-04-superlearner.qmd
        - text: "3.3 Longitudinal Case Study"
          href: advanced/03-03-longitudinal-case-study.qmd
        - text: "3.4 Effect Modification"
          href: advanced/03-04-effect-modification.qmd
        - text: "3.5 Advanced Diagnostics"
          href: advanced/03-05-advanced-diagnostics.qmd
        - text: "3.6 RWD meets RCT: Hybrid Designs"
          href: advanced/03-06-rwd-meets-rct-hybrid-designs.qmd
        - text: "3.7 Longitudinal Time-Dependent Confounding"
          href: advanced/03-07-longitudinal-td-confounding.qmd
        - text: "3.8 TMLE in the Clean Room Design"
          href: advanced/03-08-tmle-clean-room.qmd
        - text: "Covariate Adjustment in RCTs using TMLE"
          href: advanced/chapter_covariate_adjustment_tmle.qmd
        - text: "Common Pitfalls in Causal Inference"
          href: advanced/common-pitfalls.qmd


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    smooth-scroll: true

